parameters:
  netzmacht.contao_workflow.templates.headline:
    "text/html": '@@NetzmachtContaoWorkflow/sections/headline.html.twig'

  netzmacht.contao_workflow.templates.history:
    "text/html": '@@NetzmachtContaoWorkflow/sections/history.html.twig'

services:
  netzmacht.contao_workflow.view.headline_renderer:
    class: Netzmacht\ContaoWorkflowBundle\Workflow\View\Renderer\HeadlineRenderer
    arguments:
      - '@translator'
      - '%netzmacht.contao_workflow.templates.headline%'
    tags:
      - { name: netzmacht.contao_workflow.renderer, priority: -10 }

  netzmacht.contao_workflow.view.history_renderer:
    class: Netzmacht\ContaoWorkflowBundle\Workflow\View\Renderer\StateHistoryRenderer
    arguments:
      - '@netzmacht.contao_toolkit.dca.manager'
      - '@translator'
      - '@netzmacht.contao_toolkit.contao.config_adapter'
      - '%netzmacht.contao_workflow.templates.history%'
    tags:
      - { name: netzmacht.contao_workflow.renderer, priority: -10 }
