parameters:
  netzmacht.contao_workflow.transition_types:
    actions:
      step: true
      actions: true
    conditional:
      step: false
      actions: false
    workflow:
      step: false
      actions: false
