services:
  netzmacht.contao_workflow.backend.step_controller:
    class: Netzmacht\Contao\Workflow\Controller\Backend\StepController
    arguments:
      - '@netzmacht.contao_workflow.manager'
      - '@netzmacht.contao_workflow.entity_manager'
      - '@netzmacht.contao_workflow.type_registry'
      - '@templating'
      - '@router'

  netzmacht.contao_workflow.backend.transition_controller:
    class: Netzmacht\Contao\Workflow\Controller\Backend\TransitionController
    arguments:
      - '@netzmacht.contao_workflow.manager'
      - '@netzmacht.contao_workflow.entity_manager'
      - '@netzmacht.contao_workflow.type_registry'
      - '@templating'
      - '@router'
      - '@netzmacht.contao_workflow.form.factory'
