services:
  _defaults:
    public: true

  netzmacht.contao_workflow.listeners.create_user_roles_listener:
    class: Netzmacht\Contao\Workflow\Listener\CreateUserRolesListener
    arguments:
      - '@contao.framework'
      - '@netzmacht.contao_toolkit.routing.scope_matcher'
      - '@netzmacht.contao_toolkit.repository_manager'
      - '@netzmacht.contao_workflow.user'
      - '@translator'
    tags:
      - { name: 'contao.hook', hook: 'initializeSystem' }

  netzmacht.contao_workflow.listeners.dca.save_permission_callback:
    class: Netzmacht\Contao\Workflow\Backend\Dca\SavePermissionsCallbackListener
    arguments:
      - '@netzmacht.contao_toolkit.repository_manager'

  netzmacht.contao_workflow.listeners.dca.common:
    class: Netzmacht\Contao\Workflow\Backend\CommonListener

  netzmacht.contao_workflow.listeners.dca.workflow:
    class: Netzmacht\Contao\Workflow\Backend\Dca\WorkflowCallbackListener
    arguments:
      - '@netzmacht.contao_workflow.type_provider'
      - '@event_dispatcher'
      - '@netzmacht.contao_toolkit.repository_manager'

  netzmacht.contao_workflow.listeners.dca.step:
    class: Netzmacht\Contao\Workflow\Backend\Dca\StepCallbackListener
    arguments:
      - '@netzmacht.contao_workflow.type_provider'
      - '@netzmacht.contao_toolkit.dca.manager'
      - '@netzmacht.contao_toolkit.repository_manager'

  netzmacht.contao_workflow.listeners.dca.transition:
    class: Netzmacht\Contao\Workflow\Backend\Dca\TransitionCallbackListener
    arguments:
      - '@netzmacht.contao_workflow.type_provider'
      - '@netzmacht.contao_toolkit.dca.manager'
      - '@netzmacht.contao_toolkit.repository_manager'

  netzmacht.contao_workflow.listeners.dca.action:
    class: Netzmacht\Contao\Workflow\Backend\Dca\ActionCallbackListener
    arguments:
      - '@event_dispatcher'
      - '@netzmacht.contao_toolkit.repository_manager'

  netzmacht.contao_workflow.listeners.dca.state:
    class: Netzmacht\Contao\Workflow\Backend\Dca\StateCallbackListener
    arguments:
      - '@translator'
      - '@templating'
      - '@netzmacht.contao_toolkit.repository_manager'

  netzmacht.contao_workflow.listeners.workflow_actions:
    class: Netzmacht\Contao\Workflow\Backend\EventListener\WorkflowActionsListener
    tags:
      - { name: 'kernel.event_listener', event: 'netzmacht.contao_workflow.get_workflow_types', method: 'onGetWorkflowActions' }
