netzmacht.contao_workflow.backend.step:
  path: /contao/workflow/{entityId}
  defaults:
    _controller: netzmacht.contao_workflow.backend.step_controller:execute
    _scope: "backend"
    _token_check: true,
    _custom_backend_view: true
    _backend_module: workflow

netzmacht.contao_workflow.backend.transition:
  path: /contao/workflow/{entityId}/{transition}
  defaults:
    transition: null
    _controller: netzmacht.contao_workflow.backend.transition_controller:execute
    _scope: "backend"
    _token_check: true,
    _custom_backend_view: true
    _backend_module: workflow
