services:
  netzmacht.contao_workflow.user:
    class: Netzmacht\Workflow\Security\User

  netzmacht.contao_workflow.type_provider:
    class: Netzmacht\Contao\Workflow\Type\WorkflowTypeProvider
    arguments:
      - []

  netzmacht.contao_workflow.type.default:
    class: Netzmacht\Contao\Workflow\Type\DefaultWorkflowType
    tags:
      - { name: 'netzmacht.contao_workflow.type' }

  netzmacht.contao_workflow.action_factory:
    class: Netzmacht\Contao\Workflow\Action\ActionFactory
    arguments:
      - []

  netzmacht.contao_workflow.action_factory.property:
    class: Netzmacht\Contao\Workflow\Action\Property\PropertyActionFactory
    tags:
      - { name: 'netzmacht.contao_workflow.action' }

  netzmacht.contao_workflow.entity.factory:
    class: Netzmacht\Contao\Workflow\Entity\DelegatingEntityFactory
    arguments:
      - []

  netzmacht.contao_workflow.entity.factory.contao_model:
    class: Netzmacht\Contao\Workflow\Entity\ContaoModelEntityFactory
    tags:
      - { name: 'netzmacht.contao_workflow.entity.factory' }

  netzmacht.contao_workflow.transition_handler_factory:
    class: Netzmacht\Workflow\Handler\RepositoryBasedTransitionHandlerFactory

  netzmacht.contao_workflow.manager:
    class: Netzmacht\Contao\Workflow\Manager\ContaoWorkflowManager
    arguments:
      -
